bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'copy-mode -e'"
bind | split-window -h
bind - split-window -v

# Copy selected text to the macOS clipboard.
bind-key -T copy-mode MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"

set -g terminal-overrides 'xterm:colors=256'
set -g @continuum-restore 'on'
set -g @continuum-boot 'off'
